### ISSUE TITLE
Dynamic Import and vite

### ISSUE THREAD

**Issue by manfredsteyer** [picardjs/picard#2]
I think we need this comment to ease vite:

![image](https://github.com/picardjs/picard/assets/1573728/d503b19a-f497-4cb8-b84d-2774bec94d2c)

**Comment by FlorianRappl** [comment]
Indeed - but with the latest iteration that I push in a few moments that should not be the deal breaker.

Let's keep this one open until the dynamic import is resolved in a bundler-independent way!

(See you tomorrow!)

**Comment by FlorianRappl** [comment]
Should be fixed in 0.0.6 - can you give it a try? Thanks!
