### ISSUE TITLE
server entry point

### ISSUE THREAD

**Issue by manfredsteyer** [picardjs/picard#9]
Hi,

the current picard version defines this entry point in its `package.json`:

```,
    "./server": {
      "require": "./dist/server/picard.js",
      "import": "./dist/server/picard.mjs",
      "types": "./dist/server/picard.d.ts"
    }`
```

However, the referenced files are missing.

**Comment by manfredsteyer** [comment]
I think, there are further references to the ``server`` folder in the ``package.json``, in ``exports`` and in ``module and ``main``.

**Comment by FlorianRappl** [comment]
Yes that is to be renamed to "node" in 0.3.0.

**Comment by FlorianRappl** [comment]
Update shipped - latest preview package should have the right exports field.

https://www.npmjs.com/package/picard-js/v/0.3.0-pre.14
